#!/usr/bin/env python3
from pathlib import Path
from collections.abc import Iterator
import re


ROOT = Path(__file__).resolve().parent.parent
DICTS = ROOT / "common" / "dicts"
PINYIN_RE = re.compile(r"^[a-z]+$")


def entries(path: Path) -> Iterator[list[str]]:
    for line in path.read_text(encoding="utf-8").splitlines():
        if not line or line.startswith("#") or "\t" not in line:
            continue
        fields = line.split("\t")
        if len(fields[0]) == 1 and PINYIN_RE.fullmatch(fields[1]):
            yield fields


base_entries = list(entries(DICTS / "rime_ice.8105.dict.yaml"))
base_chars = {fields[0] for fields in base_entries}
base_pairs = {(fields[0], fields[1]) for fields in base_entries}
base_weights: dict[str, int] = {}
for fields in base_entries:
    if len(fields) >= 3 and fields[2].isdigit():
        base_weights[fields[0]] = max(base_weights.get(fields[0], 1), int(fields[2]))

traditional_chars: set[str] = set()
for line in (ROOT / "common" / "opencc" / "TSCharacters.txt").read_text(
    encoding="utf-8"
).splitlines():
    if line and not line.startswith("#") and "\t" in line:
        source, targets = line.split("\t", 1)
        if len(source) == 1 and source not in targets.split():
            traditional_chars.add(source)

supplement: dict[tuple[str, str], int] = {}

for fields in entries(ROOT / "common" / "luna_pinyin.dict.yaml"):
    char, code = fields[:2]
    if char not in base_chars or (char, code) in base_pairs:
        continue
    weight = 1
    if len(fields) >= 3 and fields[2].endswith("%"):
        ratio = float(fields[2][:-1]) / 100
        weight = max(1, round(base_weights.get(char, 1) * ratio))
    supplement[(char, code)] = max(supplement.get((char, code), 0), weight)

for fields in entries(DICTS / "rime_ice.41448.dict.yaml"):
    char, code = fields[:2]
    if char in base_chars or char in traditional_chars:
        continue
    if 0x4E00 <= ord(char) <= 0x9FFF:
        _ = supplement.setdefault((char, code), 1)

output = DICTS / "kuro.dict.yaml"
lines = [
    "# Rime dictionary",
    "# encoding: utf-8",
    "#",
    "# Generated by scripts/build-kuro-dict.py.",
    "# Adds Luna pronunciations for the 8105 table and non-traditional",
    "# CJK Unified Ideographs from rime_ice.41448 at low weight.",
    "",
    "---",
    "name: kuro",
    'version: "2026.07.15"',
    "sort: by_weight",
    "use_preset_vocabulary: false",
    "...",
    "",
]
for (char, code), weight in sorted(
    supplement.items(), key=lambda item: (item[0][1], -item[1], item[0][0])
):
    lines.append(f"{char}\t{code}\t{weight}")
_ = output.write_text("\n".join(lines) + "\n", encoding="utf-8")

print(f"wrote {output.relative_to(ROOT)} with {len(supplement)} entries")
